spring:
  application:
    name: FOUNDERZ

  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true

  datasource:
    driver-class-name: ${MYSQL_DRIVER}
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

security:
  token:
    issuer: ${TOKEN_ISSUER}

  cors:
    allow-hosts: ${ALLOW_HOSTS}
    allow-headers: ${ALLOW_HEADERS}
    exposed-headers: ${EXPOSED_HEADERS}